// Курируемый набор эмодзи для попапа редактора форума. Не библиотека: полный
// Unicode-каталог — это мегабайты JSON и данные без явного назначения, а тут
// нужно немного, отобрать и промаркировать. Свой список короче, без лишней
// зависимости и её потенциальных проблем на бандл/аудит кода.
//
// `k` — ключевые слова для поиска (рус + англ), через пробел, нижний регистр.

export const EMOJI_CATEGORIES = [
  {
    title: 'Часто используемые',
    icon: '🕓',
    items: [
      { c: '👍', k: 'лайк класс огонь thumbsup like good' },
      { c: '👎', k: 'дизлайк плохо thumbsdown' },
      { c: '😂', k: 'смех ржу lol laugh joy' },
      { c: '😅', k: 'пот неловко sweat awkward' },
      { c: '🔥', k: 'огонь круто fire lit' },
      { c: '❤️', k: 'сердце любовь heart love' },
      { c: '🎉', k: 'праздник ура party tada' },
      { c: '🙏', k: 'пожалуйста спасибо молитва pray please thanks' },
      { c: '😢', k: 'плачу грусть cry sad' },
      { c: '👀', k: 'глаза смотрю eyes look' },
      { c: '✅', k: 'готово done check ok' },
      { c: '💯', k: 'сто 100 percent' },
    ],
  },
  {
    title: 'Смайлы',
    icon: '😊',
    items: [
      { c: '😀', k: 'улыбка smile happy' },
      { c: '😃', k: 'улыбка радость happy' },
      { c: '😄', k: 'смех радость happy laugh' },
      { c: '😁', k: 'зубы улыбка grin' },
      { c: '😆', k: 'смех closed eyes laugh' },
      { c: '😊', k: 'улыбка смущение blush' },
      { c: '🙂', k: 'улыбка slight smile' },
      { c: '🙃', k: 'перевёрнутая улыбка upside down' },
      { c: '😉', k: 'подмигиваю wink' },
      { c: '😍', k: 'влюблён глаза сердечки heart eyes love' },
      { c: '🥰', k: 'любовь сердечки smiling hearts' },
      { c: '😘', k: 'поцелуй kiss' },
      { c: '😋', k: 'вкусно yum' },
      { c: '😜', k: 'дурачусь язык wink tongue' },
      { c: '🤪', k: 'сумасшедший zany crazy' },
      { c: '🤔', k: 'думаю thinking' },
      { c: '🤨', k: 'скепсис raised eyebrow' },
      { c: '😐', k: 'нейтрально neutral' },
      { c: '😑', k: 'без выражения expressionless' },
      { c: '😏', k: 'ухмылка smirk' },
      { c: '😒', k: 'недовольство unamused' },
      { c: '🙄', k: 'закатил глаза rolling eyes' },
      { c: '😬', k: 'неловко grimace' },
      { c: '😴', k: 'сплю sleep zzz' },
      { c: '🤤', k: 'слюни drool' },
      { c: '😷', k: 'маска болею mask sick' },
      { c: '🤒', k: 'температура болезнь thermometer sick' },
      { c: '🤕', k: 'травма бинт injured' },
      { c: '🥵', k: 'жарко hot' },
      { c: '🥶', k: 'холодно cold' },
      { c: '😵', k: 'нокаут dizzy' },
      { c: '🤯', k: 'взрыв мозга mind blown' },
      { c: '🥳', k: 'вечеринка party face' },
      { c: '😎', k: 'круто очки cool sunglasses' },
      { c: '🤓', k: 'ботан nerd' },
      { c: '🧐', k: 'монокль изучаю monocle' },
      { c: '😕', k: 'смущён confused' },
      { c: '😟', k: 'тревога worried' },
      { c: '🙁', k: 'грусть frown' },
      { c: '😮', k: 'удивление wow' },
      { c: '😲', k: 'шок astonished' },
      { c: '😨', k: 'страх fearful' },
      { c: '😰', k: 'тревожный пот anxious' },
      { c: '😥', k: 'расстроен disappointed' },
      { c: '😭', k: 'рыдаю sob cry' },
      { c: '😱', k: 'крик scream' },
      { c: '😡', k: 'злость angry rage' },
      { c: '🤬', k: 'мат ругаюсь symbols swearing' },
      { c: '🤡', k: 'клоун clown' },
      { c: '💀', k: 'смерть скелет skull dead' },
      { c: '👻', k: 'призрак ghost' },
      { c: '🤖', k: 'робот bot' },
    ],
  },
  {
    title: 'Жесты и люди',
    icon: '🙌',
    items: [
      { c: '👋', k: 'привет пока wave hi bye' },
      { c: '🤚', k: 'ладонь raised hand' },
      { c: '✋', k: 'стоп ладонь hand stop' },
      { c: '👌', k: 'окей ok' },
      { c: '🤏', k: 'немного pinch' },
      { c: '✌️', k: 'победа мир peace victory' },
      { c: '🤞', k: 'скрестил пальцы fingers crossed' },
      { c: '🤘', k: 'рок metal' },
      { c: '👊', k: 'кулак fist bump' },
      { c: '👏', k: 'аплодисменты clap' },
      { c: '🙌', k: 'ура руки вверх raised hands' },
      { c: '🤝', k: 'рукопожатие сделка handshake deal' },
      { c: '💪', k: 'сила мышца strong muscle' },
      { c: '🧠', k: 'мозг ум brain' },
      { c: '👑', k: 'корона король king queen crown' },
      { c: '🥇', k: 'золото первое место gold medal' },
      { c: '🎓', k: 'выпускник учёба graduate' },
      { c: '🕵️', k: 'детектив агент spy' },
      { c: '🧑‍💻', k: 'программист код developer coder' },
      { c: '🧑‍🎨', k: 'художник artist' },
      { c: '🧑‍🚀', k: 'космонавт astronaut' },
      { c: '🧑‍✈️', k: 'пилот pilot' },
    ],
  },
  {
    title: 'Животные и природа',
    icon: '🐾',
    items: [
      { c: '🐶', k: 'собака dog' },
      { c: '🐱', k: 'кот кошка cat' },
      { c: '🐭', k: 'мышь mouse' },
      { c: '🐹', k: 'хомяк hamster' },
      { c: '🐰', k: 'кролик заяц rabbit' },
      { c: '🦊', k: 'лиса fox' },
      { c: '🐻', k: 'медведь bear' },
      { c: '🐼', k: 'панда panda' },
      { c: '🐨', k: 'коала koala' },
      { c: '🐯', k: 'тигр tiger' },
      { c: '🦁', k: 'лев lion' },
      { c: '🐮', k: 'корова cow' },
      { c: '🐷', k: 'свинья pig' },
      { c: '🐸', k: 'лягушка frog' },
      { c: '🐵', k: 'обезьяна monkey' },
      { c: '🐔', k: 'курица chicken' },
      { c: '🐧', k: 'пингвин penguin' },
      { c: '🐦', k: 'птица bird' },
      { c: '🦉', k: 'сова owl' },
      { c: '🐺', k: 'волк wolf' },
      { c: '🐴', k: 'лошадь horse' },
      { c: '🦄', k: 'единорог unicorn' },
      { c: '🐝', k: 'пчела bee' },
      { c: '🐢', k: 'черепаха turtle' },
      { c: '🐍', k: 'змея snake' },
      { c: '🐙', k: 'осьминог octopus' },
      { c: '🐬', k: 'дельфин dolphin' },
      { c: '🐳', k: 'кит whale' },
      { c: '🦖', k: 'динозавр dino' },
      { c: '🌵', k: 'кактус cactus' },
      { c: '🌲', k: 'дерево ёлка tree' },
      { c: '🌸', k: 'цветок сакура flower' },
      { c: '🌻', k: 'подсолнух sunflower' },
      { c: '🌈', k: 'радуга rainbow' },
      { c: '⭐', k: 'звезда star' },
      { c: '🌙', k: 'луна moon' },
      { c: '☀️', k: 'солнце sun' },
      { c: '☁️', k: 'облако cloud' },
      { c: '⚡', k: 'молния lightning' },
      { c: '❄️', k: 'снег снежинка snow' },
    ],
  },
  {
    title: 'Еда и напитки',
    icon: '🍔',
    items: [
      { c: '🍏', k: 'яблоко apple' },
      { c: '🍌', k: 'банан banana' },
      { c: '🍇', k: 'виноград grapes' },
      { c: '🍓', k: 'клубника strawberry' },
      { c: '🍉', k: 'арбуз watermelon' },
      { c: '🍕', k: 'пицца pizza' },
      { c: '🍔', k: 'бургер burger' },
      { c: '🍟', k: 'картошка фри fries' },
      { c: '🌭', k: 'хот дог hotdog' },
      { c: '🍿', k: 'попкорн popcorn' },
      { c: '🍩', k: 'пончик donut' },
      { c: '🍪', k: 'печенье cookie' },
      { c: '🎂', k: 'торт день рождения cake birthday' },
      { c: '🍫', k: 'шоколад chocolate' },
      { c: '🍬', k: 'конфета candy' },
      { c: '🍎', k: 'яблоко красное apple' },
      { c: '🍒', k: 'вишня cherry' },
      { c: '🍑', k: 'персик peach' },
      { c: '🥐', k: 'круассан croissant' },
      { c: '🍗', k: 'курица нога chicken leg' },
      { c: '🍜', k: 'лапша суп noodles ramen' },
      { c: '🍣', k: 'суши sushi' },
      { c: '🍦', k: 'мороженое icecream' },
      { c: '☕', k: 'кофе coffee' },
      { c: '🍵', k: 'чай tea' },
      { c: '🥤', k: 'напиток стакан drink' },
      { c: '🍺', k: 'пиво beer' },
      { c: '🍷', k: 'вино wine' },
    ],
  },
  {
    title: 'Активности и игры',
    icon: '🎮',
    items: [
      { c: '⚽', k: 'футбол soccer ball' },
      { c: '🏀', k: 'баскетбол basketball' },
      { c: '🎮', k: 'игра геймпад game controller' },
      { c: '🕹️', k: 'джойстик joystick' },
      { c: '🎲', k: 'кубик кости dice' },
      { c: '♟️', k: 'шахматы chess' },
      { c: '🎯', k: 'мишень цель dart target' },
      { c: '🏆', k: 'кубок победа trophy win' },
      { c: '🥊', k: 'бокс перчатка boxing' },
      { c: '🎸', k: 'гитара guitar' },
      { c: '🎧', k: 'наушники headphones' },
      { c: '🎬', k: 'кино фильм movie clapper' },
      { c: '🎨', k: 'рисование арт palette art' },
      { c: '📷', k: 'камера фото camera photo' },
      { c: '🚀', k: 'ракета космос rocket space' },
      { c: '⛏️', k: 'кирка майнкрафт pickaxe minecraft' },
      { c: '🧱', k: 'блок кирпич brick block' },
      { c: '💎', k: 'алмаз diamond' },
      { c: '⚔️', k: 'меч бой sword battle' },
      { c: '🛡️', k: 'щит shield' },
      { c: '🏰', k: 'замок castle' },
    ],
  },
  {
    title: 'Объекты и символы',
    icon: '💡',
    items: [
      { c: '💡', k: 'идея лампочка idea bulb' },
      { c: '📌', k: 'закреп pin' },
      { c: '📎', k: 'скрепка paperclip' },
      { c: '📝', k: 'заметка note write' },
      { c: '📅', k: 'календарь дата calendar' },
      { c: '🔔', k: 'колокольчик уведомление bell' },
      { c: '🔒', k: 'замок закрыто lock' },
      { c: '🔓', k: 'открыто unlock' },
      { c: '🔑', k: 'ключ key' },
      { c: '⚙️', k: 'настройки шестерёнка settings gear' },
      { c: '🔗', k: 'ссылка link' },
      { c: '📦', k: 'коробка посылка box' },
      { c: '💰', k: 'деньги мешок money' },
      { c: '💸', k: 'деньги улетают money flying' },
      { c: '🎁', k: 'подарок gift' },
      { c: '⏰', k: 'будильник время alarm clock' },
      { c: '⌛', k: 'песочные часы hourglass' },
      { c: '📢', k: 'объявление громко announce' },
      { c: '❓', k: 'вопрос question' },
      { c: '❗', k: 'восклицание important' },
      { c: '⚠️', k: 'внимание warning' },
      { c: '🚫', k: 'запрет forbidden no' },
      { c: '♻️', k: 'переработка recycle' },
      { c: '✨', k: 'блеск sparkles' },
      { c: '💫', k: 'звёзды dizzy stars' },
      { c: '💥', k: 'взрыв boom' },
      { c: '💤', k: 'сон сплю sleep zzz' },
      { c: '🆗', k: 'ок ok button' },
      { c: '🆕', k: 'новое new' },
      { c: '➕', k: 'плюс plus' },
      { c: '➖', k: 'минус minus' },
      { c: '❤️‍🔥', k: 'горящее сердце heart fire' },
      { c: '💙', k: 'синее сердце blue heart' },
      { c: '💚', k: 'зелёное сердце green heart' },
      { c: '💛', k: 'жёлтое сердце yellow heart' },
      { c: '🧡', k: 'оранжевое сердце orange heart' },
      { c: '💜', k: 'фиолетовое сердце purple heart' },
      { c: '🤍', k: 'белое сердце white heart' },
      { c: '🖤', k: 'чёрное сердце black heart' },
    ],
  },
]

export const RECENT_EMOJI_STORAGE_KEY = 'pfau_forum_recent_emoji'
export const MAX_RECENT_EMOJI = 24
